apiVersion: v1
kind: Service
metadata:
  name: bank-frontend-service
spec:
  selector:
    app: bank-frontend-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP 
